#!/bin/env bash
#This program prints 1 - 100 with a while loop and inputs some things with conditions

a=1
while [ $a -le 100 ]
do
	if (( a % 3 == 0 && a % 5 == 0 ))
	then
		echo 'FizzBuzz'
	elif (( a % 5 == 0 ))
	then
		echo 'Buzz'
	elif (( a % 3 == 0 ))
	then
		echo 'Fizz'
	else
		echo $a
	fi
	((a++))
done
